# vi: ft=sh

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.

# Source other profile scripts if present and executable
if [ -d "$HOME/.profile.d" ]; then
    for profile in "$HOME/.profile.d"/*
    do
        if [ -x "$profile" ]; then
            . $profile
        fi
    done
fi


# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi
