# source all executable files in .shrc.d
if [ -d "$HOME/.shrc.d" ]; then
    for rcfile in "$HOME/.shrc.d"/*
    do
        if [ -x "$rcfile" ]; then
            . $rcfile
        fi
    done
fi

# Append to command history
export HISTSIZE=1000000
export HISTFILESIZE=1000000
setopt APPEND_HISTORY HIST_IGNORE_DUPS
