---
- name: "Update apt cache"
  apt:  update_cache=yes

- name: "Install basic software"
  apt:
      name:   '{{ item }}'
      state:  'latest'
  with_items: '{{ application_packages.all }}'


- name: "Install packages on Debian"
  apt:
      name:   '{{ item }}'
      state:  'latest'
  with_items: '{{ application_packages.debian }}'
  when: 'not "Microsoft" in ansible_kernel'


- name: "Install packages on Ubuntu"
  apt:
      name:   '{{ item }}'
      state:  'latest'
  with_items: '{{ application_packages.ubuntu }}'
  when: '(ansible_distribution == "Ubuntu") and (not "Microsoft" in ansible_kernel)'
