---
- name: "Update apt cache"
  apt:  update_cache=yes

- name: "Install basic software"
  apt:
      name:   '{{ item }}'
      state:  'latest'
  with_items: '{{ basic_packages_all }}'


- name: "Install packages on Debian"
  apt:
      name:   '{{ item }}'
      state:  'latest'
  with_items: '{{ basic_packages_debian }}'
